version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    target-branch: develop
    ignore:
      - dependency-name: "@types/node"
        versions:
          - 16.11.47
      - dependency-name: "@types/node-fetch"
        versions:
          - 2.6.2
      - dependency-name: "@types/ws"
        versions:
          - 7.4.1
      - dependency-name: discord.js
        versions:
          - 14.1.2
      - dependency-name: typescript
        versions:
          - 4.7.4
